name: ci
on: [push]
jobs:
  # runs all on local
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt clippy

      - name: cargo test
        run: cargo test --all-features

      - name: cargo clippy
        run: cargo clippy

      - name: cargo fmt
        run: cargo fmt --all -- --check
